/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonIcon: typeof import('./src/components/common/icon/index.vue')['default']
    DomainItem: typeof import('./src/components/domain/item.vue')['default']
    MainFooter: typeof import('./src/components/main/footer/index.vue')['default']
    MainFooterDeepLinks: typeof import('./src/components/main/footer/deep-links.vue')['default']
    MainFooterInput: typeof import('./src/components/main/footer/input.vue')['default']
    MainFooterScrollbar: typeof import('./src/components/main/footer/scrollbar.vue')['default']
    MainFooterScroller: typeof import('./src/components/main/footer/scroller.vue')['default']
    MainFooterSuggestions: typeof import('./src/components/main/footer/suggestions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
